export QARCHITECTURE_PATH=`$PWD/infrastructure-1.27/architecture-path`
export QINSTALLDIR=`pwd`
export PATH=$PWD/QobiScheme-1.44/${QARCHITECTURE_PATH}:$PATH
echo QARCHITECTURE_PATH=$QARCHITECTURE_PATH
echo QINSTALLDIR=$QINSTALLDIR
echo PATH=$PATH
echo done.