#!/bin/bash
export BUILD_ROOT=`pwd`
git clone git://github.com/barak/scheme2c
cd scheme2c
make forLINUX
cd LINUX/cdecl
make SCC=`which scc` all
cd ../xlib
make SCC=`which scc` scxl.a
cd ../../..
git clone --branch sanity /home/git/stalingrad.git
cd stalingrad
source environment.sh
cd QobiScheme-1.44/source
make port
cd $QARCHITECTURE_PATH
make SCXL=$BUILD_ROOT/scheme2c/LINUX/xlib "AR=ar -r" RANLIB=ranlib "LRL=QobiScheme.a \$(SCXL)/scxl.a -lX11" sch QobiScheme-AD.a
cd ../../../source
make port
cd $QARCHITECTURE_PATH
make SCXL=$BUILD_ROOT/scheme2c/LINUX/xlib "LRL=stalingradlib-stuff.o stalingradlib-double-c.o $QINSTALLDIR/QobiScheme-1.44/source/$QARCHITECTURE_PATH/QobiScheme.a \$(SCXL)/scxl.a -lX11" stalingrad
