#!/bin/tcsh -f
unlimit stack
setenv SCMAXHEAP 2048

echo none
unsetenv STALINGRAD_INLINE
unsetenv STALINGRAD_ANF_CONVERT
unsetenv STALINGRAD_ALIAS
unsetenv STALINGRAD_SRA
time ./run1

echo inline
setenv STALINGRAD_INLINE
unsetenv STALINGRAD_ANF_CONVERT
unsetenv STALINGRAD_ALIAS
unsetenv STALINGRAD_SRA
time ./run1

echo anf-convert
unsetenv STALINGRAD_INLINE
setenv STALINGRAD_ANF_CONVERT
unsetenv STALINGRAD_ALIAS
unsetenv STALINGRAD_SRA
time ./run1

echo inline anf-convert
setenv STALINGRAD_INLINE
setenv STALINGRAD_ANF_CONVERT
unsetenv STALINGRAD_ALIAS
unsetenv STALINGRAD_SRA
time ./run1

echo alias
unsetenv STALINGRAD_INLINE
unsetenv STALINGRAD_ANF_CONVERT
setenv STALINGRAD_ALIAS
unsetenv STALINGRAD_SRA
time ./run1

echo inline alias
setenv STALINGRAD_INLINE
unsetenv STALINGRAD_ANF_CONVERT
setenv STALINGRAD_ALIAS
unsetenv STALINGRAD_SRA
time ./run1

echo anf-convert alias
unsetenv STALINGRAD_INLINE
setenv STALINGRAD_ANF_CONVERT
setenv STALINGRAD_ALIAS
unsetenv STALINGRAD_SRA
time ./run1

echo inline anf-convert alias
setenv STALINGRAD_INLINE
setenv STALINGRAD_ANF_CONVERT
setenv STALINGRAD_ALIAS
unsetenv STALINGRAD_SRA
time ./run1

echo sra
unsetenv STALINGRAD_INLINE
unsetenv STALINGRAD_ANF_CONVERT
unsetenv STALINGRAD_ALIAS
setenv STALINGRAD_SRA
time ./run1

echo inline sra
setenv STALINGRAD_INLINE
unsetenv STALINGRAD_ANF_CONVERT
unsetenv STALINGRAD_ALIAS
setenv STALINGRAD_SRA
time ./run1

echo alias sra
unsetenv STALINGRAD_INLINE
unsetenv STALINGRAD_ANF_CONVERT
setenv STALINGRAD_ALIAS
setenv STALINGRAD_SRA
time ./run1

echo inline alias sra
setenv STALINGRAD_INLINE
unsetenv STALINGRAD_ANF_CONVERT
setenv STALINGRAD_ALIAS
setenv STALINGRAD_SRA
time ./run1
