#!/bin/tcsh -f

./make-clean
echo run 0
time ./run-0
./make-clean
echo run 1 3
time ./run-1-3
./make-clean
echo run 1 2
time ./run-1-2
./make-clean
echo run 1
time ./run-1
./make-clean
echo run widen lists
time ./run-widen-lists
./make-clean
