#!/bin/sh

mit-scheme --compiler -heap 6000 --batch-mode --no-init-file --eval '(set! load/suppress-loading-message? #t)' --eval '(begin (load "test-vlad") (show-time run-registered-tests) (newline) (flush-output) (%exit 0))'
