#!/bin/tcsh -f
setenv INSTALLDIR `echo ~`
setenv ARCHITECTURE_PATH `./architecture-path`
setenv INSTALLLIB ${INSTALLDIR}/lib
setenv INSTALLLIBA ${INSTALLLIB}/${ARCHITECTURE_PATH}
setenv INSTALLBIN ${INSTALLDIR}/bin
setenv INSTALLBINA ${INSTALLBIN}/${ARCHITECTURE_PATH}
setenv INSTALLINCLUDE ${INSTALLDIR}/include
setenv INSTALLINCLUDEA ${INSTALLINCLUDE}/${ARCHITECTURE_PATH}

if (! -e ${INSTALLDIR}) mkdir ${INSTALLDIR}
if (! -e ${INSTALLLIB}) mkdir ${INSTALLLIB}
if (! -e ${INSTALLLIBA}) mkdir ${INSTALLLIBA}
if (! -e ${INSTALLBIN}) mkdir ${INSTALLBIN}
if (! -e ${INSTALLBINA}) mkdir ${INSTALLBINA}
if (! -e ${INSTALLINCLUDE}) mkdir ${INSTALLINCLUDE}
if (! -e ${INSTALLINCLUDEA}) mkdir ${INSTALLINCLUDEA}

cd /tmp
rm -rf scheme2c
git clone git://git.debian.org/git/scheme2c/scheme2c.git
cd scheme2c
make forAMD64
cd AMD64
make
cd cdecl
make all
cd ../xlib
make scxl.a
cd /tmp/scheme2c

cd ~/infrastructure
cp architecture-path ${INSTALLBIN}/.
cp archive-date ${INSTALLBIN}/.
cp scc ${INSTALLBINA}/.

cd /tmp/scheme2c/AMD64
cp xlib/depth.sch ${INSTALLINCLUDE}/.
cp xlib/screen.sch ${INSTALLINCLUDE}/.
cp xlib/visual.sch ${INSTALLINCLUDE}/.
cp xlib/xarc.sch ${INSTALLINCLUDE}/.
cp xlib/xchar2b.sch ${INSTALLINCLUDE}/.
cp xlib/xcharstruct.sch ${INSTALLINCLUDE}/.
cp xlib/xclasshint.sch ${INSTALLINCLUDE}/.
cp xlib/xcolor.sch ${INSTALLINCLUDE}/.
cp xlib/xcomposestatus.sch ${INSTALLINCLUDE}/.
cp xlib/xevent.sch ${INSTALLINCLUDE}/.
cp xlib/xfontprop.sch ${INSTALLINCLUDE}/.
cp xlib/xfontstruct.sch ${INSTALLINCLUDE}/.
cp xlib/xgcvalues.sch ${INSTALLINCLUDE}/.
cp xlib/xhostaddress.sch ${INSTALLINCLUDE}/.
cp xlib/xiconsize.sch ${INSTALLINCLUDE}/.
cp xlib/ximage.sch ${INSTALLINCLUDE}/.
cp xlib/xkeyboardcontrol.sch ${INSTALLINCLUDE}/.
cp xlib/xkeyboardstate.sch ${INSTALLINCLUDE}/.
cp xlib/xlibCONSTANTS.sch ${INSTALLINCLUDE}/.
cp xlib/xlibTYPES.sch ${INSTALLINCLUDE}/.
cp xlib/xmodifierkeymap.sch ${INSTALLINCLUDE}/.
cp xlib/xpixmapformatvalues.sch ${INSTALLINCLUDE}/.
cp xlib/xpoint.sch ${INSTALLINCLUDE}/.
cp xlib/xrectangle.sch ${INSTALLINCLUDE}/.
cp xlib/xrmoptiondescrec.sch ${INSTALLINCLUDE}/.
cp xlib/xrmvalue.sch ${INSTALLINCLUDE}/.
cp xlib/xsegment.sch ${INSTALLINCLUDE}/.
cp xlib/xsetwindowattributes.sch ${INSTALLINCLUDE}/.
cp xlib/xsizehints.sch ${INSTALLINCLUDE}/.
cp xlib/xstandardcolormap.sch ${INSTALLINCLUDE}/.
cp xlib/xtextitem.sch ${INSTALLINCLUDE}/.
cp xlib/xtextitem16.sch ${INSTALLINCLUDE}/.
cp xlib/xtextproperty.sch ${INSTALLINCLUDE}/.
cp xlib/xtimecoord.sch ${INSTALLINCLUDE}/.
cp xlib/xvisualinfo.sch ${INSTALLINCLUDE}/.
cp xlib/xwindowattributes.sch ${INSTALLINCLUDE}/.
cp xlib/xwindowchanges.sch ${INSTALLINCLUDE}/.
cp xlib/xwmhints.sch ${INSTALLINCLUDE}/.
cp xlib/xws10.sch ${INSTALLINCLUDE}/.
cp xlib/xws2.sch ${INSTALLINCLUDE}/.
cp xlib/xws3.sch ${INSTALLINCLUDE}/.
cp xlib/xws4.sch ${INSTALLINCLUDE}/.
cp xlib/xws5.sch ${INSTALLINCLUDE}/.
cp xlib/xws6.sch ${INSTALLINCLUDE}/.
cp xlib/xws7.sch ${INSTALLINCLUDE}/.
cp xlib/xws8.sch ${INSTALLINCLUDE}/.
cp xlib/xws9.sch ${INSTALLINCLUDE}/.
cp xlib/xwsr4.sch ${INSTALLINCLUDE}/.
cp scsc/sccomp ${INSTALLBINA}/.
cp scrt/sci ${INSTALLBINA}/.
cp scrt/libsc.a ${INSTALLLIBA}/.
cp scrt/objects.h ${INSTALLLIBA}/.
cp scrt/options.h ${INSTALLLIBA}/.
cp scrt/predef.sc ${INSTALLLIBA}/.
cp xlib/scxl.a ${INSTALLLIBA}/.
ranlib -t ${INSTALLLIBA}/libsc.a
ranlib -t ${INSTALLLIBA}/scxl.a

rm -rf /tmp/scheme2c
