#!/bin/tcsh -f
map-closure -cps-converted -closure-converted cps
map-closure -cps-converted -closure-converted closure
map-closure -cps-converted -closure-converted even-odd
map-closure -cps-converted -closure-converted factorial
map-closure -cps-converted -closure-converted pair-procedure
map-closure -cps-converted -closure-converted set-bang
