#!/bin/tcsh -f

set EXAMPLE = $1
set L1 = $2
set L2 = $3
set L3 = $4
set L4 = $5
set L5 = $6
set L6 = $7
set L7 = $8
set L8 = $9

set POLYSTR = poly-${L1}-${L2}-${L3}-${L4}-${L5}-${L6}-${L7}-${L8}
set OUTFILE=${EXAMPLE}-${POLYSTR}.txt

if (${L1} > 0) then
  set L1opt = "-flow-size-limit ${L1}"
else
  set L1opt = ""
  endif

if (${L2} > 0) then
  set L2opt = "-real-limit ${L2}"
else
  set L2opt = ""
  endif

if (${L3} > 0) then
  set L3opt = "-closure-limit ${L3}"
else
  set L3opt = ""
  endif

if (${L4} > 0) then
  set L4opt = "-closure-depth-limit ${L4}"
else
  set L4opt = ""
  endif

if (${L5} > 0) then
  set L5opt = "-tagged-pair-limit ${L5}"
else
  set L5opt = ""
  endif

if (${L6} > 0) then
  set L6opt = "-tagged-pair-depth-limit ${L6}"
else
  set L6opt = ""
  endif

if (${L7} > 0) then
  set L7opt = "-bundle-limit ${L7}"
else
  set L7opt = ""
  endif

if (${L8} > 0) then
  set L8opt = "-bundle-depth-limit ${L8}"
else
  set L8opt = ""
  endif

set OPTIONS = "-no-warn -expression-equality-using-structural"

echo unbuff ">>" ${OUTFILE} time ./stalingrad -pp -flow-analysis\
${L1opt} ${L2opt} ${L3opt} ${L4opt} ${L5opt} ${L6opt} ${L7opt} ${L8opt}\
${OPTIONS} ${EXAMPLE}.vlad >${OUTFILE}

unbuff >>${OUTFILE} time ./stalingrad -pp -flow-analysis\
${L1opt} ${L2opt} ${L3opt} ${L4opt} ${L5opt} ${L6opt} ${L7opt} ${L8opt}\
${OPTIONS} ${EXAMPLE}.vlad
