#!/bin/tcsh -f

set EXAMPLE=$1

set OUTFILE=${EXAMPLE}-precise.txt

set OPTIONS="-no-warn -expression-equality-using-structural"

echo unbuff ">>" ${OUTFILE} time ./stalingrad -pp -flow-analysis\
${OPTIONS} ${EXAMPLE}.vlad >${OUTFILE}

unbuff >>${OUTFILE} time ./stalingrad -pp -flow-analysis\
${OPTIONS} ${EXAMPLE}.vlad
