#!/bin/bash

ulimit -s unlimited # khazad-dum imposes a default soft limit of 8192??
ulimit -d 1200000
ulimit -t 3000

SELFDIR=$(dirname $0)
TEST_DRIVER="${SELFDIR}/test-driver"

/usr/bin/time -o $1.time \
    -f "%U user %S sys %E real %P CPU %Mk maxresident\n(%Xk avgtext + %Dk avgdata)\n%I inputs + %O outputs\n(%F major + %R minor) pagefaults\n%W swaps" \
    ${TEST_DRIVER} '(read-and-try-expectation!)' < $1.expect > $1.fail

if [ -s $1.fail ]; then
    echo FAIL $1
    awk 1 $1.fail # Like cat $1.fail, but forces trailing newline if absent from $1.fail
else
    echo ok $1
fi
