#!/bin/bash

selfdir=$(dirname $0)
testdir="$selfdir/../test-runs"

mode="${1:-fast}"

dirname="$mode-$(date +"%F-at-%H-%M-%S")"
link="$testdir/last-$mode"

mkdir -p $testdir/$dirname
rm -f $link
ln -sf $dirname $link
rm -f $testdir/last
ln -sf $dirname $testdir/last
cp examples/automatic/math.vlad $testdir/$dirname
