#!/bin/tcsh -f
setenv SCMAXHEAP 4095
time stalingrad $1 factorial
time stalingrad $1 even-odd
time stalingrad $1 bug-a
time stalingrad $1 bug-b
time stalingrad $1 bug-c
time stalingrad $1 bug0
time stalingrad $1 bug1
time stalingrad $1 bug2
time stalingrad $1 bug3
time stalingrad $1 bug4
time stalingrad $1 example
time stalingrad $1 example-forward
time stalingrad $1 prefix
time stalingrad $1 sqrt
time stalingrad $1 triple
#time stalingrad $1 commute
time stalingrad $1 factor16
time stalingrad $1 hessian
#time stalingrad $1 double-agent
