#!/bin/tcsh -f
time ./backprop-R <<EOF
1
EOF
time ./backprop-R <<EOF
10
EOF
time ./backprop-R <<EOF
100
EOF
time ./backprop-R <<EOF
1000
EOF
time ./backprop-R <<EOF
10000
EOF
time ./backprop-R <<EOF
100000
EOF
time ./backprop-R <<EOF
1000000
EOF
time ./backprop-R <<EOF
10000000
EOF
