#!/bin/tcsh -f
# $Id$
setenv OPTIONS "-cps-evaluator -lazy-map-closure"
unlimit stack
echo Example 1
mzscheme <<EOF
(load "ex1.sc")
EOF
echo Example 2
mzscheme <<EOF
(load "ex2.sc")
EOF
echo Example 3
map-closure $OPTIONS ex3
echo Example 4
map-closure $OPTIONS ex4
echo Example 5
map-closure $OPTIONS ex5
echo Example 6
map-closure $OPTIONS ex6
echo Example 7
map-closure $OPTIONS ex7
echo Example 8
map-closure $OPTIONS ex8
echo Example 9
map-closure $OPTIONS ex9
echo Blume Example
map-closure $OPTIONS blume
echo Ghuloum Example
map-closure $OPTIONS ghuloum
echo Second Blume Example
map-closure $OPTIONS blume2
