#!/bin/tcsh -f
# $Id$
setenv OPTIONS "-letrec-as-y -closure-converted"
unlimit stack
echo Example 1
mzscheme <<EOF
(load "ex1.sc")
EOF
echo Example 2
mzscheme <<EOF
(load "ex2.sc")
EOF
echo Example 3
map-closure $OPTIONS ex3
echo Example 4
map-closure $OPTIONS ex4
echo Example 5
map-closure $OPTIONS ex5
echo Example 6
map-closure $OPTIONS ex6
echo Example 7
map-closure $OPTIONS -cps-converted ex7
echo Example 8
map-closure $OPTIONS -cps-converted ex8
echo Example 9
map-closure $OPTIONS -cps-converted ex9
echo Blume Example
map-closure $OPTIONS -cps-converted blume
echo Ghuloum Example
map-closure $OPTIONS -cps-converted ghuloum
