#!/bin/tcsh -f
time stalingrad $1 factorial
time stalingrad $1 even-odd
time stalingrad $1 bug4
time stalingrad $1 example-forward
time stalingrad $1 prefix
time stalingrad $1 sqrt
time stalingrad $1 triple
time stalingrad $1 commute
time stalingrad $1 hessian
time stalingrad $1 dn
time stalingrad $1 marble
#time stalingrad $1 double-agent
