#!/bin/tcsh -f
setenv SCMAXHEAP 900
echo Running factorial
time ../stalingrad $1 factorial
echo Running even-odd
time ../stalingrad $1 even-odd
echo Running bug4
time ../stalingrad $1 bug4
echo Running example-forward
time ../stalingrad $1 example-forward
echo Running prefix
time ../stalingrad $1 prefix
echo Running sqrt
time ../stalingrad $1 sqrt
echo Running triple
time ../stalingrad $1 triple
echo Running commute
time ../stalingrad $1 commute
echo Running hessian
time ../stalingrad $1 hessian
echo Running dn
time ../stalingrad $1 dn
echo Running marble
time ../stalingrad $1 marble
